# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc71ba1d2420f8270a7f8dfb60afb6468dbcd42690332d7fae5581b2f4792b50fbb0c933e52ced34eea37b8da6242a251d2d0aa855d42694c5972a7dd23f5422

test:
  secret_key_base: 179c6c4bce520bf59f06fc4bd21bc7984bfb5eba9fcdf5eb8a4dc4b64edb170a446ed15871f7aa12ff4b883986d918f12569a4796e29fbe962cee99c82b029b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
